### ISSUE TITLE
Can Aggregate depend on Get ?

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1704] opened 2021-10-08 08:54 UTC
I noticed that the Aggregate function does not depend on the Get query. For instance, on the following query, facets are always the same, whatever the 'wpsolr_type' condition.

```
{
  results: Get {
    WeaviateWooCommerce(
      limit: 10
      where: {path: ["wpsolr_type"], operator: Equal, valueString: "post"}
    ) {
      wpsolr_title
      wpsolr_product_cat_str
    }
  }
  facets: Aggregate {
    WeaviateWooCommerce(groupBy: ["wpsolr_product_cat_str"]) {
      meta {
        count
      }
      groupedBy {
        value
      }
    }
  }
}

```

I'd like to get facets related to the results instead.

Is it possible?

**Comment by laura-ham** [comment] 2021-10-13 11:52
@eostis can you give an example where you get this result (the min/max are the same) after applying a filter (with a valid filter returning some results)? I cannot reproduce this outcome.

**Comment by eostis** [comment] 2021-10-13 12:03
An example with "Equal" and "NotEqual" filter:

```
{
  facet_product_price_shoes: Aggregate {
    WeaviateWooCommerce(
      where: {path: ["wpsolr_product_cat_str"], operator: NotEqual, valueString: "Shoes"}
    ) {
      meta {
        count
      }
      wpsolr__price_f {
        minimum
        maximum
      }
    }
  }
  facet_product_price_t_shirts: Aggregate {
    WeaviateWooCommerce(
      where: {path: ["wpsolr_product_cat_str"], operator: Equal, valueString: "Shoes"}
    ) {
      meta {
        count
      }
      wpsolr__price_f {
        minimum
        maximum
      }
    }
    
  }
}

```
```
{
  "data": {
    "facet_product_price_shoes": {
      "WeaviateWooCommerce": [
        {
          "meta": {
            "count": 3
          },
          "wpsolr__price_f": {
            "maximum": 5e-324,
            "minimum": 1.7976931348623157e+308
          }
        }
      ]
    },
    "facet_product_price_t_shirts": {
      "WeaviateWooCommerce": [
        {
          "meta": {
            "count": 1
          },
          "wpsolr__price_f": {
            "maximum": 5e-324,
            "minimum": 1.7976931348623157e+308
          }
        }
      ]
    }
  }
}
```

**Comment by eostis** [comment] 2021-12-04 15:45
Tested with Weaviate 1.8.0, but aggregation on array of numbers still not giving the correct minimum/maximum figures.

**Comment by bobvanluijt** [comment] 2021-12-04 16:19
@eostis – would you mind sharing the query and output and desired outcome please?

**Comment by eostis** [comment] 2021-12-04 17:42
Query:
```
{
  search: Get {
    WeaviateWooCommerce(
      where: {path: ["wpsolr_type"], operator: Equal, valueString: "product"}
    ) {
      wpsolr__price_f
    }
  }
  stats_wpsolr__price_f: Aggregate {
    WeaviateWooCommerce(
      where: {path: ["wpsolr_type"], operator: Equal, valueString: "product"}
    ) {
      wpsolr__price_f {
        minimum
        maximum
      }
    }
  }
}
```

Output:
```
{
  "data": {
    "search": {
      "WeaviateWooCommerce": [
        {
          "wpsolr__price_f": [
            199
          ]
        },
        {
          "wpsolr__price_f": [
            99
          ]
        }
      ]
    },
    "stats_wpsolr__price_f": {
      "WeaviateWooCommerce": [
        {
          "wpsolr__price_f": {
            "maximum": 5e-324,
            "minimum": 1.7976931348623157e+308
          }
        }
      ]
    }
  }
}
```

**Comment by etiennedi** [comment] 2022-02-09 12:38
Unmark stale. This is in progress and to be released shortly.

**Comment by etiennedi** [comment] 2022-04-12 05:56
Reopen, will be part of the v1.13.0 release.

**Closed** 2022-06-23 04:48 UTC
Labels: autoclosed
