### ISSUE TITLE
Make nearText available on aggregates

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1764] opened 2021-12-09 19:35 UTC
It looks like aggregates do not support the “nearText” filter. Is it definitely not possible?

![image](https://user-images.githubusercontent.com/1785759/145463638-96ddfc66-cb36-4c6f-a7d5-3ab662a8e020.png)

**Comment by etiennedi** [comment] 2021-12-10 08:11
Hi @eostis, I think this is a duplicate of #1739, can you confirm?

**Comment by eostis** [comment] 2021-12-10 08:13
@etiennedi Indeed. I close this issue.

**Closed** 2021-12-10 08:16 UTC
