### ISSUE TITLE
[bug] OpenAI module does not support nearText on aggregations

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2108] opened 2022-08-14 18:47 UTC
Hi,

- Class definition with the OpenAI Vectorizer:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/1785759/184550484-ca039729-c58a-4756-a74f-6db758d84c43.png">

- nearFilter's aggregate error:
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/1785759/184550568-181b9ba1-4199-488c-bf41-e840ff24d8f2.png">

- Notice that the where filter is working fine:
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/1785759/184550710-948c022c-d4c5-4d38-9cb8-617c22cbee6e.png">

- Also notice that the same nearFilter's aggregate works fine with a Transformers vectorizer.

**Comment by etiennedi** [comment] 2022-08-15 11:10
Thanks for the report, we will look into it.

**Comment by etiennedi** [comment] 2022-08-15 14:20
We can reproduce this and have found the cause. A fix will be included in the upcoming release (end of august). Keeping the issue open until it's fixed. Thanks again for discovering this!

**Comment by eostis** [comment] 2022-08-15 14:52
I submit Weaviate to the same WPSOLR's Selenium automated tests as Elasticsearch, Solr, or Algolia. 

In that case, with the OpenAI module, and contrary to the other Weaviate modules, the indexing went well but the first faceted search failed !

**Closed** 2022-08-18 08:46 UTC
