### ISSUE TITLE
Alternative for fragments for  one-to-one and one-to-many relationships 

### ISSUE THREAD

**Issue by pPanda-beta** [semi-technologies/weaviate#972] opened 2019-09-09 14:01 UTC
It is very difficult to use fragments (or inline fragments) for one to many relationships. 
If we consider any other apis one to many relationships can be implemented without using fragments.
For example : _Github graphql has the following :_  
```
query {
  viewer {
    name
    repositories(last: 2) {
      nodes {
        name
        collaborators {
          nodes {
            name
          }
        }
      }
    }
  }
}
```

Which generates perfect one to many between **repository and collaborator** 

```
"{
  "data": {
    "viewer": {
      "name": "Palash Das",
      "repositories": {
        "nodes": [
          {
            "name": "RoutineSchedulerLib",
            "collaborators": {
              "nodes": [
                {
                  "name": "Supratik Basu"
                },
                {
                  "name": "Palash Das"
                }
              ]
            }
          }
        ]
      }
    }
  }
}"
```

**Also if we go by definitions fragments are used when there are multiple types with something common in between them**

**Comment by pPanda-beta** [comment] 2019-09-09 14:01
Further examples and info : https://docs.hasura.io/1.0/graphql/manual/schema/relationships/database-modelling/one-to-many.html

**Comment by etiennedi** [comment] 2019-09-10 06:34
Both the examples you linked represent a One-To-Many representation with regards to cardinality, e.g. one viewer has many repositories, one repository has many collaborators, etc.

In weaviate, we support one-to-many relationship like the above, but additionally must also be capable of "one to many types".

For example a class `Person` with the property `livesIn` might reference a `City`, `Town`, `Country`, `District`, etc. all with the same `livesIn` property. Since each one of those can have a completely different schema, the only way is to use the interface type in GraphQL.

> Also if we go by definitions fragments are used when there are multiple types with something common in between them

Correct, the common part here is that they are following the same reference property (`livesIn`), the different types are the respective linked classes. 

A pattern like the following would break for two reasons:
```gql
{
  Get {
    Things {
      Person {
        livesIn {
          name
          population
        }
      }
    }
  }
}
```

1. There is no guarantee that each of the referenced classes have a `name` or `population` property. There are no required properties in weaviate. 
2. The user is no longer capable of specifying which results they're interested in.

That's why we chose the following pattern:
```gql
{
  Get {
    Things {
      Person {
        livesIn {
          ... on Country {
            name
            population
          }
          ... on Town {
            label
           }
        }
      }
    }
  }
}
```

This solves both problems specified above, as we can clearly reference the desired schema and limit the types of results.

> It is very difficult to use fragments (or inline fragments) for one to many relationships.

Please elaborate on this, as I cannot follow this. Why would the use of inline fragments be any more difficult to use than the rest of GraphQL? In fact it is the recommended pattern for searches where results can be of many types. See https://graphql.org/learn/queries/#inline-fragments. They even list an example which is very, very close to the above:

> In this query, the hero field returns the type Character, which might be either a Human or a Droid depending on the episode argument. In the direct selection, you can only ask for fields that exist on the Character interface, such as name.
>
> To ask for a field on the concrete type, you need to use an inline fragment with a type condition. Because the first fragment is labeled as ... on Droid, the primaryFunction field will only be executed if the Character returned from hero is of the Droid type. Similarly for the height field for the Human type.

**Comment by pPanda-beta** [comment] 2019-09-11 07:49
@etiennedi 
The example you have given fits more for an use case of fragments. 
But for simpler use cases like 
Place -> ZipCode
I believe there is no need in this case for fragments since the relationship is one-to-many values of SAME TYPE.

**Comment by pPanda-beta** [comment] 2019-10-01 10:14
@etiennedi 
Any updates on this?

**Comment by etiennedi** [comment] 2019-10-07 13:34
@pPanda-beta as outlined in https://github.com/semi-technologies/weaviate/issues/972#issuecomment-529792597 there are currently no plans to "simplify" the API for simpler use cases, as this would break the capability to ever extend the schema. 

> I believe there is no need in this case for fragments since the relationship is one-to-many values of SAME TYPE.

The problem is that we have no way of telling if you are planning to keep the type the same. As soon as a second type is added (which not be relevant for your use cases, but for plenty others) the API would break, which is in my opinion far worse than having to parse an inline fragment - which is a standard GraphQL feature.

**Comment by etiennedi** [comment] 2019-10-07 13:42
A non-breaking option would be to extend the schema with a property, which - if set - make sure that only a single type can be used. In turn it could be directly resolved without an inline fragment.

So essentially the schema definition would change from:

```json
{
  "dataType": [   
    "ZipCode"
  ],
  "name": "string", 
  "cardinality": "atMostOne",
  "description": "string"
}
```
to: 
```json
{
  "dataType": [   
    "ZipCode"
  ],
  "name": "string", 
  "singleType": true,
  "cardinality": "atMostOne",
  "description": "string"
}
```

where `"singleType": true` would be newly introduced. Setting this to true, would have the following implications:
- direct resolving in GraphQL without inline fragment
- dataType must have length of exactly one
- field is immutable 

@bobvanluijt @fefi42 thoughts about this?

**Comment by bobvanluijt** [comment] 2019-10-17 19:42
From a UX perspective, can we reverse it?

so that;
1. it would be true by default.
2. it would go to false by default if +1 types.
3. one can manually set it to `false` (why would you want this?)

Please also include it in the release notes for @laura-ham and me regarding docs.

**Comment by fefi42** [comment] 2019-10-18 06:47
If `singleType = true` by default but the user is not aware of it then the query behavior would change if he adds another dataType and would break already running code right? This is why you have to explicitly opt in. Therefore `default = false`.

**Comment by etiennedi** [comment] 2019-12-18 15:22
@bobvanluijt I missed your response, but @fefi42's explanation is exactly right.

**Comment by bobvanluijt** [comment] 2019-12-20 12:24
Perfect, thanks gents 🙏

**Closed** 2020-04-13 14:29 UTC
Labels: wontfix
