### ISSUE TITLE
Index boolean not visible in /schema

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1029] opened 2019-11-14 13:58 UTC
When inspecting the schema at: `/v1/schema` the index state (true/false) isn't shown.

version: `0.21.0`

**Comment by etiennedi** [comment] 2019-11-14 16:35
![image](https://user-images.githubusercontent.com/8974479/68876512-e1561480-0704-11ea-8375-e62f252b7571.png)

I can't reproduce this, an item explicitly set to `index: false` is shown. The above is taking from the schema used in the acceptance test setup.

The only thing that's not shown is an implicit `index: true`, i.e. if the user doesn't specify anything this implies `index: true`, but since it's not set that way it currently isn't shown. Would you like to show an explicit `index: true` if the user didn't specify anything?

**Comment by etiennedi** [comment] 2019-11-14 17:53
Closing as the issue was in the [the weaviate python client](https://github.com/semi-technologies/weaviate-python-client/releases/tag/0.1.3-rc-0) and in fact not in weaviate itself.

**Closed by etiennedi** 2019-11-14 17:53 UTC
Labels: bug
