### ISSUE TITLE
Shortest Semantic Path

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1126] opened 2020-04-21 19:13 UTC
Currently, we don't know which semantic path is taken to get to a result. Ideally, this would be a meta value that one can get from the GQL results.

For example if the query `iphone` results in the obj `Company with the name Apple`. It should be able to show the path and distances.

e.g., `iphone` => `macintosh` => data obj.

**Comment by etiennedi** [comment] 2020-06-12 13:08
Closing as duplicate of #1136

**Closed by etiennedi** 2020-06-12 13:08 UTC
