### ISSUE TITLE
Search performance issues (probably due to newly introduced index locking) after upgrading from 1.15.5 to 1.16.0

### ISSUE THREAD

**Issue by illagrenan** [semi-technologies/weaviate#2351] opened 2022-11-10 11:37 UTC
I upgraded to a version [1.16.0](https://github.com/semi-technologies/weaviate/releases/tag/v1.16.0) and the Weaviate DB became very unresponsive, Aggregate as well as Get queries started to take up to tens of seconds (sometimes they timeout).

I went through the changes between [15.5](https://github.com/semi-technologies/weaviate/releases/tag/v1.15.5) and [16.0](https://github.com/semi-technologies/weaviate/releases/tag/v1.16.0) and I think the source of the problem is the newly introduced index locking in the `BatchPutObjects` function: https://github.com/semi-technologies/weaviate/pull/2288:
https://github.com/semi-technologies/weaviate/blob/d58eec498c4f720885165adae040dc40eca6bc36/adapters/repos/db/batch.go#L28-L31

In my opinion, it is not possible to concurrently insert items into the index and perform a search:
https://github.com/semi-technologies/weaviate/blob/a443443c80a00779c4b29e80b987906f2154493e/adapters/repos/db/search.go#L119-L129 
But maybe I'm completely wrong, I'm not a Go programmer, so I'm just guessing.

In my case, I update Weaviate (relatively large batches) and at the same time the user performs a Search:

![Untitled-2022-11-08-1343](https://user-images.githubusercontent.com/320373/201080520-f42ffe22-3454-48d3-9de3-fde29b490a41.svg)

After downgrading to [15.5](https://github.com/semi-technologies/weaviate/releases/tag/v1.15.5) everything runs OK again.

👉 My environment is the same as in this issue: https://github.com/semi-technologies/weaviate/issues/1897.

**Comment by etiennedi** [comment] 2022-11-10 14:58
Thanks for the report, we'll look into it.

**Comment by etiennedi** [comment] 2022-11-10 15:03
By the way, amazing investigation, this will save us a ton of time. And it really looks like you're on to something 🙏

**Comment by etiennedi** [comment] 2022-11-10 15:44
Can reproduce. Here's a simple experiment with querying while importing.

`v1.16.0` has occasional "blocked" queries:
![image](https://user-images.githubusercontent.com/8974479/201139980-1dce6aa7-bf2d-490d-8455-715f7be6ae52.png)

`v1.15.0` does not show this issue:
![image](https://user-images.githubusercontent.com/8974479/201140117-f610acdd-9f0e-49be-9058-4765719aa2e8.png)

This should be fairly straight-forward to fix. Hope we can release `v1.16.1` later today.

**Comment by etiennedi** [comment] 2022-11-10 18:12
Fixed in #2352, about to be released in `v1.16.1`. I'll keep the issue open until the release is ready.

**Comment by illagrenan** [comment] 2022-11-10 21:07
Thanks for the quick fix. I upgraded to version 1.16.1 and everything looks good so far. 👍

**Comment by etiennedi** [comment] 2022-11-15 09:01
Thanks for the confirmation.

**Closed by etiennedi** 2022-11-15 09:01 UTC
Labels: bug
