### ISSUE TITLE
[Bug] Limit removes viable results when data has been previously deleted

### ISSUE THREAD

**Issue by ywchan2005** [semi-technologies/weaviate#1765] opened 2021-12-10 07:51 UTC
Scenario A

`client.query.get( 'Article', [ 'title' ] ).with_where( where_clause ).do()` gives some results

Scenario B

`client.query.get( 'Article', [ 'title' ] ).with_where( where_clause ).with_limit( 1 ).do()` gives no result

The only difference between the two scenarios is the limit filter. It seems the limit filter is applied on to the results before the where filter. So, it seems, in this case, if the 1st data does not match our where filter and only the 2nd data in database is the desired one, the limit filter leaves only the 1st data in the list passing to where filter.

Does limit filter limit only the end result?

**Comment by etiennedi** [comment] 2021-12-10 08:15
Thanks for spotting this. That sounds like a bug, definitely not the desired behavior. Can you post a minimal reproducing example and specify the exact versions? Thanks!

**Comment by ywchan2005** [comment] 2021-12-10 09:01
after a few trials, the problem may relate to data deletion, but dont know if it's the only cause

1. create and delete data first
```
id = client.data_object.create( { 'author': 'Simon' }, 'Article', vector=np.random.rand( 1, 128 ) )
client.data_object.delete( id )
```
2. and re-create data
```
client.data_object.create( { 'author': 'Simon' }, 'Article', vector=np.random.rand( 1, 128 ) )
```

3. query without limit filter gives the desired data
```
results = client.query.get( 'Article', [ 'author' ] ).with_where( {
  'path': 'author',
  'operator': 'Equal',
  'valueText': 'Simon',
} ).do()
```
4. and query with limit filter gives none
```
results = client.query.get( 'Article', [ 'author' ] ).with_where( {
  'path': 'author',
  'operator': 'Equal',
  'valueText': 'Simon',
} ).with_limit( 1 ).do()
```

**Comment by etiennedi** [comment] 2021-12-10 09:12
Thank you for the reproducing example, this will definitely help in investigating this! One more question: Which weaviate version are you running this with?

**Comment by ywchan2005** [comment] 2021-12-10 09:40
sorry for missing the information

the version is 1.8.0

**Comment by etiennedi** [comment] 2021-12-14 10:51
Hi @ywchan2005,

thanks again for reporting this and the great reproducing example. We have been able to reproduce this and a fix is on the way which will be part of the next release. If you need a fix more urgent than that, please let me know and I can provide you with an intermediary Docker image that contains the fix - even before the next release.

We have also added new tests to prevent a regression on this issue.

In case you are interested in what was going on, let me try to explain:

- Internally each object has a numerical (`uint64`) document id which we use in the inverted index. In your example the first object you created has doc id `0` and the second you created had doc id `1`
- Since you were using a filter, you were making use of the inverted index. If a delete had never occurred, the entry for the value `Simon` would have been `[0, 1]` for both doc ids. 
- There was a bug with regards to cleaning up the inverted index, so when we deleted object `0`, we never cleaned up the entry for `Simon`, so the row still was as is.
- With a high limit you wouldn't notice because Weaviate would just look at both ids and decide that `0` no longer exists, so it would only serve you with `1`. However, when the limit was `1` weaviate would first cut off the results, so it only contains `[0]`. Then it would find out that this object no longer exists and return no results. 
- After the fix it would only ever get back `[1]` so even after truncating the list, the correct result is still on there :)

**Closed** 2021-12-14 13:23 UTC
Labels: bug
